apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: ifconfigme-http
spec:
  hosts:
  - ifconfig.me
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
